name: "Bot Commit & Push"
description: "Commit and push changes with github-actions[bot]"

inputs:
  scope:
    required: true
    description: "Scope in Commit message"

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '25'

    - name: run ${{ inputs.scope }}
      env:
        PPS_INTEGRATION_NOTION: ${{ secrets.PPS_INTEGRATION_NOTION }}
      run: ./gradlew :${{ inputs.scope }}:bootRun
      shell: bash

    - name: commit & push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add storage/
        git commit \
          -m "chore(${{ inputs.scope }}): ${{ inputs.scope }} Notion JSONs at $(date -u +'%Y-%m-%d %H:%M:%S')" \
          -m "$(git diff --cached --name-status)" \
          || echo "✅ No changes to commit"
        git push "https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git"
      shell: bash
