name: "Setup Environment"
description: "Checkout code, setup Java, setup SSH with DEPLOY_KEY"

inputs:
  DEPLOY_KEY:
    description: "SSH private key for GitHub deploy"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 25

    - name: Setup SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
