description: |
  - Setup Java
  - Setup SSH with DEPLOY_KEY
  - Clone target repo
  - Run Gradle
inputs:
  key:
    description: "SSH private key for GitHub deploy"
    required: true
  token:
    description: "Integration token of Notion objects"
    required: false
  domain:
    description: "Business domain scope"
    required: true
  batch:
    description: "Batch job scope"
    required: true
  dir:
    description: "Path file name of directory that the Spring Boot run on"
    required: false
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 25
    - run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts 2>/dev/null
      shell: bash
    - run: |
        git clone --depth=1 git@github.com:wliamp/storage-${{ inputs.domain }}.git \
          ${{ runner.temp }}/${{ inputs.domain }}/storage
      shell: bash
    - run: ./gradlew :${{ inputs.batch }}:bootRun
      env:
        NOTION_INTEGRATION_TOKEN: ${{ inputs.token }}
        DIRECTORY_TEMP: ${{ runner.temp }}/${{ inputs.domain }}/${{ inputs.dir }}
      shell: bash
