name: "Setup Environment & Run Application"
description: "Checkout code, setup Java, setup SSH with DEPLOY_KEY, clone target repo, run Gradle"

inputs:
  key:
    description: "SSH private key for GitHub deploy"
    required: true
  token:
    description: "Integration token of Notion objects"
    required: false
  notion:
    description: "Notion Workspace name / Module in Spring Boot project"
    required: true
  module:
    description: "Backup / Cleanup / Storage"
    required: true
  dir:
    description: "Clone temp directory path file name"
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 25

    - name: Setup SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Clone
      shell: bash
      run: |
        git clone --depth=1 git@github.com:wliamp/notion-storage-${{ inputs.notion }}.git \
          ${{ runner.temp }}/${{ inputs.notion }}/${{ inputs.dir }}

    - name: Run
      shell: bash
      env:
        NOTION_INTEGRATION_TOKEN: ${{ inputs.token }}
        DIRECTORY_TEMP: ${{ runner.temp }}/${{ inputs.notion }}/${{ inputs.module }}
      run: ./gradlew :${{ inputs.module }}:bootRun
