name: Backup
on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string
    secrets:
      DEPLOY_KEY:
        required: true
      NOTION_INTEGRATION_TOKEN:
        required: true
jobs:
  backup:
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-run
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          token: ${{ secrets.NOTION_INTEGRATION_TOKEN }}
          domain: ${{ inputs.domain }}
          batch: backup
          dir: backup
      - run: |
          rm -rf ./*
          cp -r ${{ runner.temp }}/${{ inputs.domain }}/backup/* .
        working-directory: ${{ runner.temp }}/${{ inputs.domain }}/storage
      - uses: ./.github/actions/commit-clean
        with:
          domain: ${{ inputs.domain }}
          batch: backup
    runs-on: ubuntu-latest
