name: Notion Backup

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: commit & push
      uses: ./.github/actions/git-commit
      with:
        scope: "backup"

