name: Notion Backup

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Run Notion backup
        env:
          PPS_INTEGRATION_NOTION: ${{ secrets.PPS_INTEGRATION_NOTION }}
        run: ./gradlew :backup:bootRun

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add storage/
          git commit \
            -m "chore(backup): backup Notion JSONs at $(date -u +'%Y-%m-%d %H:%M:%S')" \
            -m "$(git diff --cached --name-status)" \
            || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

