on:
  workflow_call:
    inputs:
      module:
        required: true
        type: string
    secrets:
      DEPLOY_KEY:
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-run
        with:
          key: ${{ secures.DEPLOY_KEY }}
          module: ${{ inputs.module }}

      - uses: ./.github/actions/commit-clean
        with:
          module: ${{ inputs.module }}

