name: Storage Cleanup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: commit & push
        uses: ./.github/actions/git-commit
        with:
          scope: "cleanup"
