name: Cleanup Payment
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  cleanup-payment:
    uses: ./.github/workflows/cleanup.yml
    with:
      domain: payment
    secrets:
      DEPLOY_KEY: ${{ secrets.PPS_DEPLOY_KEY }}
