name: PPS Backup

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  backup:
    uses: ./.github/workflows/commit-push.yml
    with:
      module: "pps"
      scope: "backup"
    secrets:
      NOTION_INTEGRATION_TOKEN: ${{ secrets.PPS_INTEGRATION_NOTION }}
