name: PPS Backup

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  pss:
    uses: ./.github/workflows/backup.yml
    with:
      module: "pps"
    secrets:
      DEPLOY_KEY: ${{ secrets.PPS_DEPLOY_KEY }}
      NOTION_INTEGRATION_TOKEN: ${{ secrets.PPS_INTEGRATION_NOTION }}
