name: Storage Cleanup

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Commit & Push
        uses: ./.github/actions/git-commit
        with:
          module: "pps"
          scope: "cleanup"
